#!/ usr/bin/env python


def grid(m,n):
#defining the funtion of grid with size m number of rwos and n number of columns
    if m == 0 or n==0: return 1
#if the grid  index is at  0 and index 1  is less than 0,return 1 and the number of route is zero
    routes = 0
    if m > 0:
#when the grid index is at 0 and the value at index 0 is greater than 0, then enter the if loop and perform the condition
#number of routes is determined
       routes = routes + grid(m-1,n)
    if n > 0:
#when the grid index 1 has value greater than 0 enter into the if statement and execute the condition   
#find the number of routes
       routes = routes + grid(m,n-1)
#the routes from both the if statements are added and total number of routes are stored in routes
# routes is then returned after excuting the program
    return routes
# equation to find the number of routes :
# from the statements of if
#Eg :- routes of grid(2,3) + routes of  grid(3,2) = routes of grid(3,3)
grid(20,20)
#when executed grid(20,20) the number of routes from top left corner to bottom right corner of the grid(20,20) is determined
